# Convolution 

A convolution is a mathematical operation on two functions that produces a third function expressing how the shape of one is modified by the other. It is a fundamental building block of Convolutional Neural Networks (CNNs).

### 1D Convolution

For a 1D signal `f` and a kernel `g`, the discrete convolution `(f * g)` at a point `n` is defined as:

$$
(f * g)[n] = \sum_{m} f[m] \cdot g[n - m]
$$

This is equivalent to flipping the kernel, sliding it along the signal, and computing the sum of element-wise products at each position.

### 2D Convolution

For a 2D image `I` and a kernel `K`, the convolution at a point `(i, j)` is:

$$
(I * K)(i, j) = \sum_{m} \sum_{n} I(m, n) \cdot K(i - m, j - n)
$$

This operation is used for feature detection, where the kernel is designed to detect specific patterns like edges, corners, or textures.

## 2D convolution 

In [1]:
def convolve(signal, kernel):
    output = []
    kernel_size = len(kernel)
    padding = kernel_size // 2 # assume zero padding
    padded_signal = [0] * padding + signal + [0] * padding

    for i in range(padding, len(signal) + padding):
        sum = 0
        for j in range(kernel_size):
            sum += kernel[j] * padded_signal[i - padding + j]
        output.append(sum)

    return output


In [2]:
import numpy as np


def convolve_2(signal, kernel):
    output = []
    kernel_size = len(kernel)
    padding = kernel_size // 2 # assume zero padding
    padded_signal = [0] * padding + signal + [0] * padding

    for i in range(0,  len(padded_signal) - padding ):
        total = sum([k* v for k,v in zip(kernel, padded_signal[i:i+kernel_size], strict=False)])
        output.append(total)

    return output


In [3]:
signal = [1, 2, 3, 4, 5, 6]
kernel = [1, 0, -1]
output1 = convolve(signal, kernel)
output2 = convolve_2(signal, kernel)

print(output1)
print(output2)



[-2, -2, -2, -2, -2, 5]
[-2, -2, -2, -2, -2, 5, 6]


## 3D convolution 

In [4]:

def convolution(image, kernel):
    # get the size of the input image and kernel
    (image_height, image_width, image_channels) = image.shape
    (kernel_height, kernel_width, kernel_channels) = kernel.shape

    # calculate the padding needed for 'same' convolution
    pad_h = (kernel_height - 1) // 2
    pad_w = (kernel_width - 1) // 2

    # pad the input image with zeros
    padded_image = np.pad(image, ((pad_h, pad_h), (pad_w, pad_w), (0, 0)), 'constant')

    # create an empty output tensor
    output_height = image_height
    output_width = image_width
    output_channels = kernel_channels
    output = np.zeros((output_height, output_width, output_channels))

    # perform the convolution operation
    for i in range(output_height):
        for j in range(output_width):
            for k in range(output_channels):
                output[i, j, k] = np.sum(kernel[:, :, k] * padded_image[i:i+kernel_height, j:j+kernel_width, :])

    return output


In [5]:
# create an example image and kernel
image = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
kernel = np.array([[[1, 0], [0, -1]], [[0, 1], [-1, 0]]])

# perform the convolution operation
output = convolution(image, kernel)

print('Input image:')
print(image)

print('\nKernel:')
print(kernel)

print('\nOutput:')
print(output)


Input image:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

Kernel:
[[[ 1  0]
  [ 0 -1]]

 [[ 0  1]
  [-1  0]]]

Output:
[[[-6.  2.]
  [-2. -2.]]

 [[-6.  2.]
  [-2. -2.]]

 [[-3.  1.]
  [-1. -1.]]]
